config/routes.rb
Rails.application.routes.draw do
    root "operation#index"

  get 'operations/new' => 'operation#new'
  post 'operation/answer' => 'operation#answer'
  get 'operation/answer' => 'operation#answer'
  resources :operation

  get 'movies/search' => 'movies#search'
  post 'movies/search' => 'movies#search', as: :search
  get 'movies/index' => 'movies#index'
  post 'movies/index' => 'movies#index', as: :index
  resources :games
  resources :movies

  resources :genders

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def search
    q = ""
    q = params[:movies][:query] if params[:movies]
    @result = Movie.search(q)
    respond_to do |format|
        format.html {@result}
        format.js {}
        format.json { render json: @result }
    end
  end




  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movies_path, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :gender_id, :description)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <%= f.input :name %>
  <%= f.association :gender %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<%= javascript_include_tag "jquery.tablesorter.js"%>
<script>
    $(document).ready(function()
        {
            $("#domainsTable").tablesorter({sortList: [[3,1],[2,0]]});
        }
    );
    </script>

<style>

table {
    border-collapse: collapse;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #f2f2f2;
    color: black;
}
.head{
    background-color: #4CAF50;
    color: white;
}
.title{
    text-align: center;
    vertical-align: middle;
}

</style>
<h1 class="title">Movies Database</h1>

<%= link_to 'New Movie', new_movie_path %>
<%= link_to 'Search', search_path %>
<table class="tablesorter" id ="domainsTable">
  <thead>
    <tr>
      <th class="head">Name</th>
      <th class="head">Genero</th>
      <th class="head">Description</th>
      <th class="head">Show</th>
      <th class="head">Edit</th>
      <th class="head">Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.gender.name if !movie.gender.nil? %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movies/new.html.erb
<style media="screen">
.simple_form div.input {
margin-bottom: 10px;
clear: both; /* Required for Webkit, but not for Gecko */
text-align: center;
}

.simple_form label {
align-items: center;
width: 100px;
text-align: right;
margin: 2px 10px;
}

div.boolean, .simple_form input[type='submit'] {
margin-left: 50%;
}

div.boolean label, label.collection_radio_buttons {
float: none;
margin: 0;
}

label.collection_radio_buttons {
margin-right: 10px;
vertical-align: -2px;
margin-left: 2px;
}

.field_with_errors {
background-color: #ff3333;
}

.simple_form .error {
clear: left;
color: black;
display: block;
margin-left: 120px;
}

.simple_form .hint {
clear: left;
margin-left: 120px;
color: #555;
display: block;
font-style: italic;
}

input.radio {
margin-right: 5px;
vertical-align: -3px;
}

.center{

    text-align: center;
}
</style>

<h1 class="center">New movie</h1>
<br>
<br>
<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<style type="text/css">
em{
  color: red;
}

.button{
    text-align: center
}
.form-inline div { display: inline-block }
abbr[title="required"] {
  display: none;
}
table {
    border-collapse: collapse;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #f2f2f2;
    color: black;
}
.head{
    background-color: #4CAF50;
    color: white;
}
.title{
    text-align: center;
    vertical-align: middle;
}

</style>

<script type="text/javascript">
$('#sayt').bind('keyup', function() {
    console.log("estoy dentro");
    $('form#sayt').trigger('submit.rails');
});
</script>

<h1 id="title" style="text-align: center">New search</h1>
<br>
<%= link_to 'Main', index_path %>
<br>
<div class="button">
<%= simple_form_for :movies, :remote => true, :html => { :class => "form-inline", :id => "sayt"} do |f| %>

  <%= f.input :query, :label => "", :id => "sayt" %>
  <%= f.submit :search %>
  </div>
<% end %>

<div>
<table >
    <thead>
        <tr>
            <th class="head">Name</th>
            <th class="head">Descripcion</th>
        </tr>
    </thead>
    <tbody id = "datos">
    </tbody>
</table>

</div>

app/views/movies/search.js.erb
console.log(<%= raw(@result.to_json)%>)
var result = <%= raw(@result.to_json)%>
document.getElementById("datos").innerHTML = "";
function foreachmovie(element, index, array){
$(document.getElementById("datos")).append("<tr>"+"<td>"+element["_source"].name+"</td>"+"<td>"+element.highlight.description[0]+"</td>" + "</tr>\n");}


result.forEach(foreachmovie);

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @movie.gender.name %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>