config/routes.rb
Rails.application.routes.draw do
    root "operation#index"

  get 'operations/new' => 'operation#new'
  post 'operation/answer' => 'operation#answer'
  get 'operation/answer' => 'operation#answer'
  resources :operation

  get 'movies/search' => 'movies#search'
  post 'movies/search' => 'movies#search', as: :search
  get 'movies/index' => 'movies#index'
  post 'movies/index' => 'movies#index', as: :index
  resources :games
  resources :movies

  resources :genders

end

app/models/operation.rb
class Operation
  include Mongoid::Document
  include Mongoid::Enum

  after_create :calculate_result_estimation



  #enum, :operations [:add, :sub, :mul, :div]
#["+", "-", "*", "/"]
  field :op, type: String
  field :time0, type: Float
  field :time1, type: Float
  field :timetot, type: Float
  field :num1, type: Integer
  field :num2, type: Integer
  field :resultado, type: Integer
  field :estimacion, type: String

  def total_time
      update_attributes(timetot: (time1 - time0))
  end

  def check_result(result)
      resultado == result
  end

 # def estimate
#      self.estimation = HTTP.get("http://localhost:5000/predict/#{op1.to_f}/").to_s
 # end

  private
    def calculate_result_estimation
        table = Hash["+" => 0, "-" => 1, "*" => 2, "/" => 3]
        update_attributes(resultado: num1.public_send(op,num2))
        update_attributes(estimacion: HTTP.get("http://localhost:5000/predict/#{num1.to_f}/#{num2.to_f}/#{table[op].to_f}/").to_s)
    end
end

app/controllers/operation_controller.rb
def getrandom
  oper = ["+", "-", "*", "/"]
  return oper.sample
end

def submit(op1, op2, oper, res)
  puts op1, op2

end

class OperationController < ApplicationController

  # GET /peliculas/new
  def index

  end

  def new
      operator = ["+", "-", "*", "/"].sample
      operator = "+"
      @operation = Operation.create({
          time0: Time.new,
          num1: rand(1..99),
          num2: rand(1..99),
          op: operator
    })
  end

  def answer
      @operation = Operation.find(params[:id])
      if @operation.check_result(params[:operation][:resultado].to_i)
        @operation.update_attributes(time1: Time.now)
        @operation.total_time
        @operation.save
        flash[:success] = "Right!"
      else
          flash[:error] = "Wrong!"
          render :new
      end
  end
end

app/helpers/operation_helper.rb
module OperationHelper
end

app/views/operation/_form.html.erb
<%= form_for(@pelicula) do |f| %>
  <% if @pelicula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pelicula.errors.count, "error") %> prohibited this pelicula from being saved:</h2>

      <ul>
      <% @pelicula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operation/answer.html.erb
<style media="screen">
h1, h4, p{
    text-align: center;
    vertical-align: middle;
}
</style>
<h1>Gran trabajo, operacion realizada</h1>
<br>
<br>
<h4>Has tardado:
    <%= @operation.timetot%>
</h4>

<h4>Se estimaba:
    <%= @operation.estimacion%>
</h4>

<% if @operation.timetot < @operation.estimacion.to_f%>
<p>
    Gran trabajo, eres mas rapido que la mayoria
</p>
<% else %>
<p>
    Has sido demasiado lento!
</p>
<%end%>
<%= link_to 'Otra mas', new_operation_path %>

app/views/operation/index.html.erb
<h1 style="text-align: center">Bienvenido!!  <br> <br> Vamos a operar</h1>
<%= link_to 'Start', new_operation_path %>

app/views/operation/new.html.erb
<style>
table {
    border-collapse: collapse;
}

th, td {
    text-align: left;
    padding: 8px;
}


th {
    background-color: #f2f2f2;
    color: black;
}
.head{
    background-color: #4CAF50;
    color: white;
}
.title{
    text-align: center;
    vertical-align: middle;
}
</style>
<h1 class="title">Opera</h1>
<table align= "center">
    <head>
        <tr>
            <th class="head">operando 1</th>
            <th class="head">operacion</th>
            <th class="head">operando 2</th>
            <th class="head">resultado</th>
            <th class="head">estimacion</th>
        </tr>
    </head>
    <br>
    <tbody>
        <br>
        <tr>
            <th><%=@operation.num1%></th>
            <th><%=@operation.op%></th>
            <th><%=@operation.num2%></th>
            <th>
                <%= form_for @operation, url: { action: "answer", id: @operation.id }, html: { method: "answer" } do |f| %>
                <%= f.text_field :resultado, :value => "" %>

                <%= f.submit 'Submit', :name => "join" %>
            </th>
            <th>
                <%=@operation.estimacion%>
                <% end %>
            </th>
        </tr>
    </tbody>
</table>
<br>