config/routes.rb
Rails.application.routes.draw do
    root "operation#index"

  get 'operations/new' => 'operation#new'
  post 'operation/answer' => 'operation#answer'
  get 'operation/answer' => 'operation#answer'
  resources :operation

  get 'movies/search' => 'movies#search'
  post 'movies/search' => 'movies#search', as: :search
  get 'movies/index' => 'movies#index'
  post 'movies/index' => 'movies#index', as: :index
  resources :games
  resources :movies

  resources :genders

end

app/models/gender.rb
class Gender
  include Mongoid::Document
  field :name, type: String
  has_many :movies
end

app/controllers/genders_controller.rb
class GendersController < ApplicationController
  before_action :set_gender, only: [:show, :edit, :update, :destroy]

  # GET /genders
  # GET /genders.json
  def index
    @genders = Gender.all
  end

  # GET /genders/1
  # GET /genders/1.json
  def show
  end

  # GET /genders/new
  def new
    @gender = Gender.new
  end

  # GET /genders/1/edit
  def edit
  end

  # POST /genders
  # POST /genders.json
  def create
    @gender = Gender.new(gender_params)

    respond_to do |format|
      if @gender.save
        format.html { redirect_to @gender, notice: 'Gender was successfully created.' }
        format.json { render :show, status: :created, location: @gender }
      else
        format.html { render :new }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genders/1
  # PATCH/PUT /genders/1.json
  def update
    respond_to do |format|
      if @gender.update(gender_params)
        format.html { redirect_to @gender, notice: 'Gender was successfully updated.' }
        format.json { render :show, status: :ok, location: @gender }
      else
        format.html { render :edit }
        format.json { render json: @gender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genders/1
  # DELETE /genders/1.json
  def destroy
    @gender.destroy
    respond_to do |format|
      format.html { redirect_to genders_url, notice: 'Gender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gender
      @gender = Gender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gender_params
      params.require(:gender).permit(:name)
    end
end

app/views/genders/_form.html.erb
<%= simple_form_for(@gender) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/genders/edit.html.erb
<h1>Editing gender</h1>

<%= render 'form' %>

<%= link_to 'Show', @gender %> |
<%= link_to 'Back', genders_path %>

app/views/genders/index.html.erb
<h1>Listing genders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genders.each do |gender| %>
      <tr>
        <td><%= gender.name %></td>
        <td><%= link_to 'Show', gender %></td>
        <td><%= link_to 'Edit', edit_gender_path(gender) %></td>
        <td><%= link_to 'Destroy', gender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gender', new_gender_path %>

app/views/genders/new.html.erb
<h1>New gender</h1>

<%= render 'form' %>

<%= link_to 'Back', genders_path %>

app/views/genders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gender.name %>
</p>

<%= link_to 'Edit', edit_gender_path(@gender) %> |
<%= link_to 'Back', genders_path %>